In [4]:
import pandas as pd

In [5]:
# Obtenemos la Data sobre Indicadores Básicos del Desempeño Ambiental - Residuos peligrosos

# Listamos las URL de las fuentes de datos origen, para poder realizar la ingesta
urls = [
    'http://dsiappsdev.semarnat.gob.mx/datos/indicadores/dambiental/Residuos%20peligrosos/volumen%20de%20residuos%20peligrosos%20reportado%20por%20empresas%20a%20semarnat.csv',
    'http://dsiappsdev.semarnat.gob.mx/datos/indicadores/dambiental/Residuos%20peligrosos/sitios%20con%20residuos%20peligrosos%20remediados%20o%20en%20remediacion.csv',
    'http://dsiappsdev.semarnat.gob.mx/datos/indicadores/dambiental/Residuos%20peligrosos/volumen%20fisico%20de%20produccion%20manufacturero%20y%20minero.csv',
    'http://dsiappsdev.semarnat.gob.mx/datos/indicadores/dambiental/Residuos%20peligrosos/auditorias%20ambientales.csv',
    'http://dsiappsdev.semarnat.gob.mx/datos/indicadores/dambiental/Residuos%20peligrosos/cumplimiento%20de%20normatividad%20en%20residuos%20peligrosos.csv',
    'http://dsiappsdev.semarnat.gob.mx/datos/indicadores/dambiental/Residuos%20peligrosos/sitios%20contaminados%20registrados.csv'
]

In [7]:
for url in urls:
    df = pd.read_csv(url)
    print(df.head())

         AÑO  GENERACION_ACUMULADA_(TONELADAS_ACUMULADAS_POR_PERIODO)
0  2004-2009                                         1699635.04
1  2004-2011                                         1920408.13
2  2004-2012                                         1958231.34
3  2004-2013                                         2035068.85
4  2004-2014                                         2193336.45
    AÑO            TIPO_DE_SITIO  CANTIDAD_(NUMERO)
0  2008  Emergencias Ambientales                142
1  2008      Pasivos Ambientales                479
2  2008        Sitios Remediados                 76
3  2009  Emergencias Ambientales                135
4  2009      Pasivos Ambientales                465
      AÑO         SECTOR  VOLUMEN_FISICO_(INDICE_DE_VOLUMEN_FISICO)
0  1993.0         Minero                                      102.0
1  1993.0  Manufacturero                                       65.0
2  1994.0         Minero                                       98.0
3  1994.0  Manufacturero                                       68.0
4  1995.0         Minero                                      109.0
    AÑO  AUDITORIAS_INICIADAS_(NUMERO)
0  1992                             97
1  1993                            185
2  1994                            387
3  1995                            294
4  1996                            333
    AÑO   RESULTADO_DE_LAS_VISITAS  RESULTADO_(PORCENTAJE)
0  2004  Clausura parcial temporal                    0.65
1  2004    Clausura total temporal                    0.66
2  2004        Sin irregularidades                   27.60
3  2004      Irregularidades leves                   71.10
4  2005  Clausura parcial temporal                    0.61
    AÑO  SITIOS_CONTAMINADOS_REGISTRADOS_(NUMERO)
0  1995                                       166
1  1996                                       166
2  1997                                       166
3  1998                                       166
4  1999                                       166

In [8]:
# Ingesta
df_recolecion = pd.read_csv('http://dsiappsdev.semarnat.gob.mx/datos/residuos/Rubro8_Recoleccion_y_Transporte_de_residuos_peligrosos.csv')

In [9]:
df_recolecion.head()

,No.,Empresa,Direccisn,Municipio,Clave Municipio,Estado,Clave Entidad,Telifono,Tipo de residuo,No. de Autorizacisn,Vigencia Inicio,Vigencia Termino,Capacidad Toneladas.,Unnamed: 13
0,1,Servicios Industriales Ecologicos (Javier Maci...,Angel Gonzalez No. 11,Aguascalientes,1.0,Aguascalientes,1.0,NaN,Identificados como peligrosos de la Norma Ofic...,1-1-PS-I-01-94,20/12/1994,Indefinida,NaN,NaN
1,2,Juan Carlos Ibarra Torres,"Francisco Sarabia No. 314, Col. Altavista, C.P...",Aguascalientes,1.0,Aguascalientes,1.0,01 44 91 87 86 25,Acumuladores elictricos de electrolito lmquido...,09-001-PS-II-24D-15,11/09/2015,11/09/2025,1.63,NaN
2,3,"Solver, S.A. de C.V.","Meseta de Chema No. 2500, Col. Monte de los Ol...",Tijuana,4.0,Baja California,2.0,NaN,Recoleccisn de transporte de residuos de soluc...,2-4-PS-V-01-93,05/01/1994,Indefinida,NaN,NaN
3,4,"Ingenieria y Ecologia, S.A. de C.V.",Rmo fuerte y Felipe Angeles No. 599 Col. Vallarta,Mexicali,2.0,Baja California,2.0,NaN,Recoleccisn de transporte de solventes organi...,2-2-PS-I-04-94,03/05/1994,Indefinida,NaN,NaN
4,5,"Industrias P. Kay de Mixico, S.A. de C.V.","Calle de la Brea No. 3, Meseta de Chema, Col. ...",Tijuana,4.0,Baja California,2.0,NaN,Recoleccisn de transporte de escorias de solda...,2-4-PS-I-05-94,22/06/1994,Indefinida,NaN,NaN

In [ ]:
# Ingesta: Inventario Nacional de Emisiones de Gases y Compuestos de Efecto Invernadero (INEGyCEI)

In [12]:
# Ordenamiento Ecológico del Territorio Modalidad Local
# URL: https://datos.gob.mx/busca/dataset/ordenamiento-ecologico-del-territorio-modalidad-local
df_ordeco = pd.read_csv('http://dsiappsdev.semarnat.gob.mx/datos/POET_local.csv', encoding='latin')

In [16]:
df_ordeco

      Año  Estado  Monto federal otorgado  Modalidad
0   2014.0  México           $3,018,296.00     Local
1   2014.0  Oaxaca           $3,576,200.00     Local
2      NaN     NaN                     NaN       NaN
3      NaN     NaN                     NaN       NaN
4      NaN     NaN                     NaN       NaN
5      NaN     NaN                     NaN       NaN
6      NaN     NaN                     NaN       NaN
7      NaN     NaN                     NaN       NaN
8      NaN     NaN                     NaN       NaN
9      NaN     NaN                     NaN       NaN
10     NaN     NaN                     NaN       NaN
11     NaN     NaN                     NaN       NaN
12     NaN     NaN                     NaN       NaN
13     NaN     NaN                     NaN       NaN
14     NaN     NaN                     NaN       NaN
15     NaN     NaN                     NaN       NaN
16     NaN     NaN                     NaN       NaN
17     NaN     NaN                     NaN       NaN

In [17]:
# Ordenamiento Ecológico del Territorio Modalidad Regional
# URL: https://datos.gob.mx/busca/dataset/ordenamiento-ecologico-del-territorio-modalidad-regional
df_ord_eco_regional = pd.read_csv('http://dsiappsdev.semarnat.gob.mx/datos/POET_regional.csv', encoding='latin')

In [20]:
df_ord_eco_regional

    Año      Estado  Monto federal otorgado   Modalidad
0   2014      Colima           $1,100,000.00   Regional
1   2014     Durango             $899,980.27   Regional
2   2014     Hidalgo           $5,985,000.00   Regional
3   2014     Jalisco           $3,092,421.70   Regional
4   2014      México           $8,470,404.00   Regional
5   2014      Oaxaca           $1,190,000.00  Regional
6   2014     Sinaloa           $2,000,000.00   Regional
7   2014     Tabasco           $2,478,038.70   Regional
8   2015     Chiapas             $538,800.00   Regional
9   2015      Colima           $1,078,000.00   Regional
10  2015     Hidalgo           $4,116,000.00   Regional
11  2015     Jalisco          $10,878,018.66   Regional
12  2015      México           $9,127,200.00   Regional
13  2015  Tamaulipas           $4,300,057.24   Regional

In [22]:
# Programa Sectorial de Medio Ambiente y Recursos Naturales
# https://datos.gob.mx/busca/dataset/programa-sectorial-de-medio-ambiente-y-recursos-naturales
df_programa_sectorial = pd.read_csv('http://dsiappsdev.semarnat.gob.mx/datos/promarnat_2013_2018.csv', encoding='latin')

In [23]:
df_programa_sectorial

,No. del Indicador,Objetivo No.,Nombre del indicador:,Línea base 2013,Meta 2014,Resultado 2014,Meta 2015,Resultado 2015,Meta 2016,Resultado 2016,Meta 2017,Resultado 2017,Meta 2018,Avances al 30/06/2018,Unidad de medida,Observaciones 1,Observaciones 2,Observaciones 3
0,1,1,Valor de la Producción de los Bienes y Servici...,1.07,1.19,1.04,1.36,1.031,1.55,1.061,1.81,N.D.,2.14,N.D.,% del PIB,Este indicador no puede ser actualizado para 2...,NaN,NaN
1,2,1,Intensidad de carbono,50.07,N.D.,N.D.,N.D.,N.D.,N.D.,N.D.,59.4,N.D.,34.88,N.D.,tCO2e / millones de pesos a precios de 2008,En 2015 el INECC publicó el Inventario Naciona...,NaN,NaN
2,3,1,Empleos verdes,"695,409","777,146","776,214","823,775","774,358","877,732","788,397","936,415","874,372","1,000,000",N.D.,Empleos,Esta versión de la información incluye mejoras...,NaN,NaN
3,4,2,Emisiones de GEI per cápita.,5.81,N.D.,N.D.,N.D.,N.D.,N.D.,N.D.,5.63,N.D.,4.59,N.D.,tCO2e / habitante,En 2015 el INECC publicó el Inventario Naciona...,NaN,NaN
4,5,2,Disminución de la vulnerabilidad mediante infr...,0.2,---,0.34,0.37,0.38,N.A.,N.A.,0.48,0.49,0.6,N.D.,Índice,El resultado del índice se obtuvo con el cálcu...,NaN,NaN
5,6,2,Superficie con POET o PDU formulados que integ...,33,49,48.6,51,53.14,53,53.1,53.24,55.1,75,N.A.,Porcentaje,Cifras a diciembre de 2017. A partir de 2014 e...,NaN,NaN
6,7,3,Cobertura de agua potable,92,92.7,92.4,93,92.4,93.3,93.3,93.7,94.5,94,N.D.,% de cobertura,El dato definitivo se conoce con el cierre de ...,NaN,NaN
7,8,3,Decretos de reserva de agua para uso ambiental...,0,0,2,0,2,31,6,75,2,189,13,cuencas con decreto publicado,Los dos decretos publicados en el Diario Ofici...,Los trece decretos publicados en el Diario Ofi...,NaN
8,9,3,Productividad del agua en distritos de riego (...,1.62,1.71,1.79,1.75,1.75,1.79,N.D.,1.83,N.D.,1.87,N.D.,kg/m3,El periodo que contemplan las estadísticas agr...,NaN,NaN
9,10,4,Superficie conservada por medio de sistemas de...,12.92,12.63,11.52,13.21,13.73,13.35,15.91,13.65,16.29,17,16.29,% terrestre y aguas continentales,Para la línea base 2013 no se consideró el ...,NaN,NaN
10,10,4,Superficie conservada por medio de sistemas de...,0,1.5,1.54,1.89,1.78,1.9,22.29,10,22.29,10,22.29,% marino,Para la línea base 2013 no se consideró el ...,NaN,NaN
11,11,4,Superficie rehabilitada o con acciones de rest...,"80,519","333,262","505,379","557,636","694,082","727,156","783,947.60","893,676","980,575.75","1,116,500","982,914.25",hectáreas,"A partir de 2014 se reportan datos acumulados,...",NaN,NaN
12,12,4,Valor de la producción obtenida a partir del a...,"22,841","25,251","22,548","28,533","26,233","32,183","28,015","38,392","29,711","45,682",N.D.,millones de pesos,Valores preliminares sujetos a la actualizació...,NaN,NaN
13,13,5,Pérdida de capital natural,5,4.9,4.7,4.8,N.D.,4.7,N.D.,4.6,N.D.,4.5,N.D.,Porcentaje del PIB,La línea base 2013 consideró el dato de la pub...,NaN,NaN
14,14,5,Cobertura de tratamiento de aguas residuales m...,47.5,52.5,52.7,55,57,57.5,57.5,60,63,63,N.D.,Porcentaje,Las cifras definitivas se publican cada cinco ...,NaN,NaN
15,15,5,Índice de manejo integral de residuos,70,74.33,73.05,76.5,73.6,78.67,75.2,78.67,75.2,83,N.D.,Porcentaje,No se han registrado cambios al valor del inid...,NaN,NaN
16,16,6,Índice de Participación Ciudadana en el Sector...,1,1.07,1.48,1.14,1.29,1.21,1.3,1.27,1.27,1.28,N.D.,número,El valor 2017 es definitivo.,NaN,NaN
17,17,6,Índice de sustentabilidad ambiental de la com...,0.9,0.92,0.93,0.94,N.D.,0.96,N.D.,0.98,N.D.,1,N.D.,número,Valores inferiores a 1 significan que la compe...,NaN,NaN

In [24]:
# Indicadores clave - Residuos
# https://datos.gob.mx/busca/dataset/indicadores-clave--residuos
df_ind_residuos = pd.read_csv('http://dsiappsdev.semarnat.gob.mx/datos/indicadores/clave/residuos%20solidos%20urbanos%20depuestos%20sin%20control.csv')

In [25]:
df_ind_residuos

     AÑO  VOLUMEN_DEPUESTO_SIN_CONTROL
0   1997                      16655.12
1   1998                      12945.92
2   1999                      13286.45
3   2000                      13096.47
4   2001                      12141.93
5   2002                      12182.37
6   2003                      10954.80
7   2004                      11401.84
8   2005                      11344.00
9   2006                      11423.40
10  2007                      10971.30
11  2008                      10880.00
12  2009                      10725.00
13  2010                      10123.40
14  2011                       9519.40
15  2012                       8679.61

In [26]:
# Agua Residual que recibe tratamiento
# Agua residual que recibe tratamiento por entidad federativa
# https://datos.gob.mx/busca/dataset/agua-residual-que-recibe-tratamiento
df_agua_fed = pd.read_csv('http://dsiappsdev.semarnat.gob.mx/datos/Tratamiento_X_ent_federativa.csv')

In [29]:
df_agua_fed

,ENTIDAD FEDERATIVA,AÑO,CAUDAL / GENERADO (litros por segundo),CAUDAL / TRATADO (litros por segundo),TRATADO/ GENERADO (porcentaje)
0,Aguascalientes,2009,2744,3354,122.24
1,Baja California,2009,6040,5620,93.05
2,Baja California Sur,2009,1960,1063,54.22
3,Campeche,2009,2042,97,4.76
4,Chiapas,2009,6137,969,15.80
...,...,...,...,...,...
155,Tamaulipas,2013,7931,5692,71.80
156,Tlaxcala,2013,1825,786,43.10
157,Veracruz,2013,14183,5612,39.60
158,Yucatán,2013,4925,130,2.60
159,Zacatecas,2013,4634,1645,35.50

In [31]:
# Agua Residual que recibe tratamiento
# Agua residual que recibe tratamiento
# https://datos.gob.mx/busca/dataset/agua-residual-que-recibe-tratamiento
df_agua_tratamiento = pd.read_csv('http://dsiappsdev.semarnat.gob.mx/datos/Tratamiento.csv')

In [32]:
df_agua_tratamiento

,AÑO,MUNICIPAL / GENERADO (metros cúbicos/segundo),INDUSTRIAL / GENERADO (metros cúbicos/segundo),TOTAL / GENERADO (metros cúbicos/segundo),MUNICIPAL / TRATADO (metros cúbicos/segundo),INDUSTRIAL / TRATADO (metros cúbicos/segundo),TOTAL / TRATADO (metros cúbicos/segundo),TRATADO RESPECTO AL GENERADO / MUNICIPAL (porcentaje),TRATADO RESPECTO AL GENERADO / INDUSTRIAL (porcentaje),TRATADO RESPECTO AL GENERADO / TOTAL (porcentaje)
0,1998,239.00,159.48,398.48,40.85,21.95,62.81,17.09,13.76,15.76
1,1999,239.00,170.00,409.00,42.40,22.02,64.42,17.74,12.95,15.75
2,2000,250.00,169.87,419.87,45.93,25.28,71.21,18.37,14.88,16.96
3,2001,252.00,171.45,423.45,50.81,25.35,76.16,20.16,14.79,17.99
4,2002,252.00,170.60,422.60,56.15,26.23,82.38,22.28,15.38,19.49
5,2003,255.30,171.00,426.30,60.24,27.39,87.63,23.60,16.01,20.56
6,2004,255.17,178.00,433.17,64.54,27.40,91.94,25.29,15.39,21.22
7,2005,265.63,178.00,443.63,71.78,26.82,98.60,27.02,15.07,22.23
8,2006,242.10,183.00,425.10,74.39,27.66,102.05,30.73,15.11,24.01
9,2007,242.81,188.70,431.51,79.29,29.87,109.16,32.66,15.83,25.30
10,2008,235.84,190.40,426.24,83.64,33.78,117.42,35.46,17.74,27.55
11,2009,237.46,190.40,427.86,88.13,36.70,124.83,37.11,19.28,29.17
12,2010,235.08,212.60,447.68,93.60,63.60,157.20,39.82,29.91,35.11
13,2011,236.35,207.30,443.65,97.64,50.40,148.04,41.30,24.31,33.37
14,2012,229.74,209.80,439.54,99.75,60.50,160.25,43.42,28.84,36.46
15,2013,230.62,210.26,440.88,105.94,60.75,166.69,45.93,28.89,37.81

In [33]:
# Almacenamiento (acopio)
# https://datos.gob.mx/busca/dataset/almacenamiento-acopio
df_acopio = pd.read_csv('http://dsiappsdev.semarnat.gob.mx/datos/residuos/Rubro9_Almacenamiento_y_Acopio_de_residuos_peligrosos.csv')
df_acopio

,No.,Empresa,Direccisn,Municipio,Clave Municipio,Estado,Clave Entidad,Telifono,Tipo de residuo,No. de Autorizacisn,Vigencia Inicio,Vigencia Termino,Capacidad Toneladas
0,1,Juan Antonio Ibarra Torres,"Francisco Sarabia, No. 314, col Altavista, C.P...",Aguascalientes,1.0,Aguascalientes,1.0,44 9187 8625,Acumulador usado,09-001-PS-II-26D-15,25/10/2015,25/10/2025,NaN
1,2,"Suministros Ambientales Mexicanos, S.A de C.V.","Calle Cuyamaca Lote 17-B,Colonia Plutarco Elei...",Mexicali,2.0,Baja California,2.0,(686) 839 55 55,"Aceite usado, Lodos con solventes, pinturas, a...",02-002-PS-II-02-D-2015,01/02/2015,01/02/2025,"1,289.00"
2,3,"VLS Recovery Services de Mixico, S.A. de C.V.",Calle Nueve Sur No.113 Col. Ciudad Industrial ...,Tijuana,4.0,Baja California,2.0,Tel. (664)623-5200 ext. 127,Aceites gastados de corte y enfriamiento en la...,02-II-05-17,18/10/2017,18/10/2027,686
3,4,"Pochteca Materias Primas, S.A. de C.V","Calle 5 Norte, No. 109-722\nCol. Ciudad Indust...",Tijuana,4.0,Baja California,2.0,NaN,solventes gastados\nlistado 1\ngiro 1: benefic...,02-004-PS-II-01-D-2021,20/04/2021,20/04/2031,"3,200.00"
4,5,"Grupo Ambiental Del Noroeste, S. de R.L. de C.V.","Calle Maquiladoras, No. 1469,\nColonia, Cd. In...",Tijuana,4.0,Baja California,2.0,N/D,Solidos Peligrosos De La Nom-052-Semarnat-2005...,02-004-PS-II-03-D-2021,08/04/2021,08/04/2031,"24,312.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,463,"Inlubsa, S.A. de C.V.","Calle Cantera No. 13-17, Colonia Parque Indust...",Guadalupe,17.0,Zacatecas,32.0,13336561238,"Aceite lubricante gastado, agua contaminada co...",32-17-PS-II-014-D-15,19/09/2015,19/09/2025,843.6
463,464,Protec Medica S.A de C.V.,"Entronque a Genaro Codina s/n Km 3, Carretera ...",Genaro Codina,12.0,Zacatecas,32.0,4929820116,"Sangre, cultivos y cepas de agentes biolsgicos...",32-12-PS-II-14-17,04/02/2017,04/02/2027,"4,368.00"
464,465,Sara Abigail Hernandez Urenda,"Antigua Carretera Panamericana Km 4.5, la esco...",Zacatecas,56.0,Zacatecas,32.0,(492) 92 4 99 82 y 7687254,"Aceite lubricante usado, tierra contaminada co...",32-56-PS-II-16-17,20/06/2017,20/06/2027,"4,000.00"
465,466,"Repuestos de Zacatecas, S.A. de C.V.","Av. Plateros #909, Colonia las Arboledas",Frenillo,10.0,Zacatecas,32.0,(493)9358555,Acumuladores Usados,32-10-PS-II-18-17,06/07/2017,06/07/2027,500
466,467,Fidencio Del Rio Esparza Sucesores S.A. de C.V.,"5 de mayo #72, Centro",Guadalupe,17.0,Zacatecas,32.0,92 3 05 50,Acumuladores Usados,32-17-PS-II-19-17,09/11/2017,09/11/2027,30

In [34]:
df_acopio.Estado.unique()

array(['Aguascalientes', 'Baja California', ' Baja California',
       'Baja California Sur', 'Campeche', 'Chihuahua', 'Chihuahua ',
       'Coahuila ', 'Colima', 'Ciudad de Mixico', 'Ciudad de Mixico ',
       'Durango', 'Guanajuato', 'Guanajuato ', 'Guerrero', 'Hidalgo',
       'Hidalgo ', 'Jalisco', 'JALISCO', 'Mixico', 'Michoacan de Ocampo',
       'Morelos', 'Nayarit', 'Nuevo Lesn', 'Miguel Hidalgo  ',
       'Nuevo Lesn ', 'Oaxaca', 'Puebla', 'Queritaro', 'San Luis Potosm',
       'Tabasco', 'Tamaulipas', 'Tlaxcala',
       'Veracruz de Ignacio de la Llave', 'Veracruz', 'Yucatan ',
       'Yucatan', 'Zacatecas '], dtype=object)

In [35]:
# Superficie de Conservación Recuperada (SEDEMA)
# https://datos.cdmx.gob.mx/dataset/indicadores-monitor-estadistico-de-la-ciudad-de-mexico
df_conservacion = pd.read_csv('https://datos.cdmx.gob.mx/dataset/5b938119-7d49-491f-9eba-09cd4f7241b5/resource/bfb72f62-a09e-43c2-8035-1794063fc0d0/download/superficie-conservacion.csv')

In [37]:
df_conservacion

        fecha  ciudad_de_mexico
0  2016-01-01            113.25
1  2017-01-01            117.85
2  2018-01-01            134.45
3  2019-01-01            221.65
4  2020-01-01            405.29
5  2021-01-01            492.86

# Red Manual de Monitoreo Atmosférico (REDMA)

La Red de Meteorología y Radiación Solar (REDMET) es el subsistema del Sistema de Monitoreo Atmosférico de la Ciudad de México (SIMAT) que realiza mediciones periódicas cada 6 días de partículas suspendidas totales (PST), partículas menores a 10 micrómetros, plomo en partículas suspendidas totales (Pb PST), partículas menores a 2.5 micrómetros. (PM25)

Link [https://datos.cdmx.gob.mx/dataset/redma](https://datos.cdmx.gob.mx/dataset/redma)

In [38]:
df_redma = pd.read_csv('https://datos.cdmx.gob.mx/dataset/1729ac65-a3c5-46ab-a851-71a983795598/resource/12769c73-8bb9-4244-ad60-2dc8e2ab7ddc/download/redma_2023_05.csv')

In [41]:
df_redma

          fecha    PbPST       PM10       PM25         PST
0    2015-01-06  0.01645  37.625000  20.428571   97.500000
1    2015-01-12  0.02672  64.000000  33.285714  118.800000
2    2015-01-18  0.01704  48.750000  23.166667   99.200000
3    2015-01-24  0.01814  55.625000  24.166667  115.200000
4    2015-01-30  0.01896  56.750000  25.833333  127.400000
..          ...      ...        ...        ...         ...
507  2023-05-06      NaN  63.142857  27.000000  140.000000
508  2023-05-12      NaN  49.571429  25.000000  116.000000
509  2023-05-18      NaN  42.600000  19.600000   91.500000
510  2023-05-24      NaN  46.142857  23.333333   92.666667
511  2023-05-30      NaN  39.125000  18.666667   86.000000

[512 rows x 5 columns]

In [42]:
from hashlib import sha1

def compute_hash(email):
    return sha1(email.encode('utf-8')).hexdigest()

def compute_certificate_id(email):
    email_clean = email.lower().strip()
    return compute_hash(email_clean + '_')

In [43]:
cohort = 2024
course = 'dezoomcamp'
your_id = compute_certificate_id('kiramishima@outlook.com')
url = f"https://certificate.datatalks.club/{course}/{cohort}/{your_id}.pdf"
print(url)

https://certificate.datatalks.club/dezoomcamp/2024/76a8a824601a2fc5b4833741e238851ef5604702.pdf